BOARD_TAG = attiny45-8
MONITOR_PORT = /dev/ttyUSB0
ARDUINO_DIR = $(HOME)/.arduino
ISP_PROG = stk500v1
ISP_PORT = /dev/ttyUSB0
AVRDUDE_ISP_BAUDRATE = 9600
AVRDUDE_OPTS = -F -q
USER_LIB_PATH = lib
ARDUINO_LIBS =

include /usr/share/arduino/Arduino.mk
